### ISSUE TITLE
spec changes backlog

### ISSUE THREAD

**Issue by devsnek** [engine262/engine262#164]
- [ ] [`9ff2ef4`](https://github.com/tc39/ecma262/commit/9ff2ef4) Editorial: restore exponent in NumericValue (#2450)
- [ ] [`aafbfe4`](https://github.com/tc39/ecma262/commit/aafbfe4) Editorial: comparisons in number stringification are of floats, not reals (#2450)
- [ ] [`66ecf7b`](https://github.com/tc39/ecma262/commit/66ecf7b) Editorial: fix typo in Number.prototype.toExponential (#2450)
- [ ] [`cae7692`](https://github.com/tc39/ecma262/commit/cae7692) Editorial: Drop grammatical parameters from 'use' productions (#2446)
- [ ] [`47568ca`](https://github.com/tc39/ecma262/commit/47568ca) Editorial: refactor runtime MV and add/use RoundStringMVResult (#2435)
- [ ] [`af5467d`](https://github.com/tc39/ecma262/commit/af5467d) Editorial: Define+use "list-concatenation" (#2383)
- [ ] [`45021b4`](https://github.com/tc39/ecma262/commit/45021b4) Meta: fix auto-deployment (#2453)
- [ ] [`f469441`](https://github.com/tc39/ecma262/commit/f469441) Editorial: Clarify the AsyncGenerator state machine (#2413)
- [ ] [`d3e7c43`](https://github.com/tc39/ecma262/commit/d3e7c43) Editorial: have Create{,Async}IteratorFromClosure provide a new execution context to GeneratorStart (#2398)
- [ ] [`ef4b237`](https://github.com/tc39/ecma262/commit/ef4b237) Meta: bump ecmarkup to 8.0.0 (#2452)
- [ ] [`7a79833`](https://github.com/tc39/ecma262/commit/7a79833) Meta: fix passing PR number (see #2260)
- [ ] [`80efe41`](https://github.com/tc39/ecma262/commit/80efe41) Meta: add debug info (see #2260)
- [ ] [`b4e31f6`](https://github.com/tc39/ecma262/commit/b4e31f6) Meta: migrate from travis-ci to Github Actions (#2260)
- [ ] [`6d3c629`](https://github.com/tc39/ecma262/commit/6d3c629) Editorial: use abstract closures in MakeArg{Getter,Setter} (#2439)
- [ ] [`08d2018`](https://github.com/tc39/ecma262/commit/08d2018) Editorial: use abstract closure in Proxy.revocable (#2439)
- [ ] [`5872981`](https://github.com/tc39/ecma262/commit/5872981) Editorial: use abstract closures in AsyncGeneratorResumeNext (#2439)
- [ ] [`a5645b0`](https://github.com/tc39/ecma262/commit/a5645b0) Editorial: use abstract closure in Promise.prototype.finally (#2439)
- [ ] [`9254e1a`](https://github.com/tc39/ecma262/commit/9254e1a) Editorial: use abstract closure in NewPromiseCapability (#2439)
- [ ] [`b268083`](https://github.com/tc39/ecma262/commit/b268083) Editorial: use abstract closure in AsyncFromSyncIteratorContinuation (#2439)
- [ ] [`148089b`](https://github.com/tc39/ecma262/commit/148089b) Editorial: use abstract closure for default constructor (#2439)
- [ ] [`2ae1ebb`](https://github.com/tc39/ecma262/commit/2ae1ebb) Editorial: use abstract closures in Await (#2439)
- [ ] [`fbdf389`](https://github.com/tc39/ecma262/commit/fbdf389) Editorial: Add support for Abstract Closures to `CreateBuiltinFunction` (#2109)
- [ ] [`61cc329`](https://github.com/tc39/ecma262/commit/61cc329) Meta: CONTRIBUTING.md: Some changes to make the doc more beginner-friendly (#2431)
- [ ] [`c7d208f`](https://github.com/tc39/ecma262/commit/c7d208f) Editorial: Make IsLessThan's _LeftFirst_ param required (#2378)
- [ ] [`19d7ca4`](https://github.com/tc39/ecma262/commit/19d7ca4) Editorial: Recast "Strict Equality Comparison" (#2378)
- [ ] [`c7d6d1c`](https://github.com/tc39/ecma262/commit/c7d6d1c) Editorial: Recast "Abstract Equality Comparison" (#2378)
- [ ] [`587adc0`](https://github.com/tc39/ecma262/commit/587adc0) Editorial: Recast "Abstract Relational Comparison" (#2378)
- [ ] [`28fb25e`](https://github.com/tc39/ecma262/commit/28fb25e) Editorial: fix note about var decls in eval in parameter initializers (#2428)
- [ ] [`3d8c15c`](https://github.com/tc39/ecma262/commit/3d8c15c) Editorial: emu-notes in AOs go before "It performs..." (#2427)
- [ ] [`8b4556e`](https://github.com/tc39/ecma262/commit/8b4556e) Editorial: put WaiterList in its own clause (#2427)
- [ ] [`3efa10e`](https://github.com/tc39/ecma262/commit/3efa10e) Editorial: consistency for preambles Create*Iterator AOs (#2427)
- [ ] [`bdca6e1`](https://github.com/tc39/ecma262/commit/bdca6e1) Editorial: make preamble for LocalTZA consistent with other AOs (#2427)
- [ ] [`4f48e83`](https://github.com/tc39/ecma262/commit/4f48e83) Editorial: move *Instantiation notes to after their preambles (#2427)
- [ ] [`a4098f5`](https://github.com/tc39/ecma262/commit/a4098f5) Editorial: algorithms constraining memory model are not AOs (#2427)
- [ ] [`c1441b6`](https://github.com/tc39/ecma262/commit/c1441b6) Editorial: drop remaining uses of Concrete Method suffix (#2427)
- [ ] [`6b4724f`](https://github.com/tc39/ecma262/commit/6b4724f) Editorial: consistency for FlattenIntoArray's optional args (#2427)
- [ ] [`1272a59`](https://github.com/tc39/ecma262/commit/1272a59) Editorial: fix handling of infinities in Math.hypot (#2426)
- [ ] [`9f53106`](https://github.com/tc39/ecma262/commit/9f53106) Editorial: `meta` should be listed alongside target (#2416)
- [ ] [`33fe30f`](https://github.com/tc39/ecma262/commit/33fe30f) Editorial: fix typo in Iterator Interface "next" requirements (#2424)
- [ ] [`f7264bb`](https://github.com/tc39/ecma262/commit/f7264bb) Editorial: Change ValidateTypedArray so that it doesn't return the buffer (#2376)
- [ ] [`0ea8d7b`](https://github.com/tc39/ecma262/commit/0ea8d7b) Meta: bump ecmarkup to 7.1.0 (#2419)
- [ ] [`fa21a5b`](https://github.com/tc39/ecma262/commit/fa21a5b) Editorial: consistency for capitalization in notes (#2419)
- [ ] [`c2a9389`](https://github.com/tc39/ecma262/commit/c2a9389) Normative: Make SharedArrayBuffer's sole parameter required (#2393)
- [ ] [`56b5e8b`](https://github.com/tc39/ecma262/commit/56b5e8b) Normative: Add public and private class fields, static class features, private methods & getters/setters
- [ ] [`c754979`](https://github.com/tc39/ecma262/commit/c754979) Editorial: more explicit validation in CreateDynamicFunction (#2374)
- [ ] [`26061c0`](https://github.com/tc39/ecma262/commit/26061c0) Editorial: suppress spurious linking of "Contains" (#2369)
- [ ] [`417a0bb`](https://github.com/tc39/ecma262/commit/417a0bb) Editorial: Fix Contains algorithm of ClassTail (#2362)
- [ ] [`bbaac2f`](https://github.com/tc39/ecma262/commit/bbaac2f) Editorial: Simplify CreateDynamicFunction (#2348)
- [ ] [`a12b4d4`](https://github.com/tc39/ecma262/commit/a12b4d4) Editorial: Correct usage of 'Let'/'Set' in various algorithms (#2365)
- [ ] [`02dcd23`](https://github.com/tc39/ecma262/commit/02dcd23) Editorial: Factor out abstract operation RegExpHasFlag (#2349)
- [ ] [`c4c8aae`](https://github.com/tc39/ecma262/commit/c4c8aae) Editorial: Consistent notation of newly created error object (#2363)
- [ ] [`7cea37d`](https://github.com/tc39/ecma262/commit/7cea37d) Editorial: Unfold SDO `CoveredFormalsList` (#2350)
- [ ] [`b751864`](https://github.com/tc39/ecma262/commit/b751864) Editorial: Eliminate one use of SDO `CoveredFormalsList` (#2350)
- [ ] [`1db56bd`](https://github.com/tc39/ecma262/commit/1db56bd) Editorial: Unfold SDO `CoveredAsyncArrowHead` (#2350)
- [ ] [`7d7bde4`](https://github.com/tc39/ecma262/commit/7d7bde4) Editorial: Unfold SDO `CoveredCallExpression` (#2350)
- [ ] [`54d61b8`](https://github.com/tc39/ecma262/commit/54d61b8) Editorial: Unfold SDO `CoveredParenthesizedExpression` (#2350)
- [ ] [`40279cf`](https://github.com/tc39/ecma262/commit/40279cf) Editorial: Fix early error rules of 'IfStatement' (#2359)
- [ ] [`d7e5ba9`](https://github.com/tc39/ecma262/commit/d7e5ba9) Editorial: Change "includes" to "contains" (#2351)
- [ ] [`a484294`](https://github.com/tc39/ecma262/commit/a484294) Editorial: Change "headings" to "heading" (#2351)
- [ ] [`1635e8b`](https://github.com/tc39/ecma262/commit/1635e8b) Editorial: Drop Script Record's [[Environment]] field (#2351)
- [ ] [`7289f37`](https://github.com/tc39/ecma262/commit/7289f37) Editorial: Change "that is the same sign as _number_" (#2351)
- [ ] [`2e3e086`](https://github.com/tc39/ecma262/commit/2e3e086) Editorial: 5 simple tweaks that I believe are self-explanatory (#2351)
- [ ] [`416c1ae`](https://github.com/tc39/ecma262/commit/416c1ae) Editorial: clean up wording of Array and TypedArray methods (#2346)
- [ ] [`e726760`](https://github.com/tc39/ecma262/commit/e726760) Editorial: remove redundant `index.html` (#2344)
- [ ] [`4746d71`](https://github.com/tc39/ecma262/commit/4746d71) Meta: bump ecmarkup to 7.0.3 (#2344)
- [ ] [`d911ee2`](https://github.com/tc39/ecma262/commit/d911ee2) Editorial: use target alias name instead of "it" (#2341)
- [ ] [`dae76f8`](https://github.com/tc39/ecma262/commit/dae76f8) Editorial: Rename alias `_bindings_` to `_bindingObject_` (#2287)
- [ ] [`d7be463`](https://github.com/tc39/ecma262/commit/d7be463) Editorial: Introduce fields to specify object Env Rec (#2287)
- [ ] [`90d7dbb`](https://github.com/tc39/ecma262/commit/90d7dbb) Editorial: Add parameter to NewObjectEnvironemt (#2287)
- [ ] [`12f93fd`](https://github.com/tc39/ecma262/commit/12f93fd) Editorial: Set _withEnvironment_ explicitly (#2287)
- [ ] [`f8ecdd0`](https://github.com/tc39/ecma262/commit/f8ecdd0) Editorial: Have NewGlobalEnvironment invoke NewObjectEnvironment (#2287)
- [ ] [`0635793`](https://github.com/tc39/ecma262/commit/0635793) Normative: Use HostJobCallbacks for FinalizationRegistry callbacks (#2316)
- [ ] [`3cd00d7`](https://github.com/tc39/ecma262/commit/3cd00d7) Meta: multipage builds (#2339)
- [ ] [`e584010`](https://github.com/tc39/ecma262/commit/e584010) Meta: bump ecmarkup to 7.0.2 (#2339)
- [ ] [`750b51c`](https://github.com/tc39/ecma262/commit/750b51c) Normative: specify creation order for capturing group properties (#2329)
- [ ] [`dd25b44`](https://github.com/tc39/ecma262/commit/dd25b44) Editorial: Clarify ES2021 Array.prototype.sort change (#2342)
- [ ] [`634295a`](https://github.com/tc39/ecma262/commit/634295a) Meta: update editors list for ES2022
- [ ] [`1f748a4`](https://github.com/tc39/ecma262/commit/1f748a4) Editorial: master is now ES2022
- [ ] [`a53b61f`](https://github.com/tc39/ecma262/commit/a53b61f) Editorial: add ES2021 intro text
- [ ] [`f12df86`](https://github.com/tc39/ecma262/commit/f12df86) Meta: better compression during preview uploads (#2340)
- [ ] [`d9fea48`](https://github.com/tc39/ecma262/commit/d9fea48) Editorial: Align checks order in [[DefineOwnProperty]] overrides with ordinary method (#2333)
- [ ] [`5c79427`](https://github.com/tc39/ecma262/commit/5c79427) Editorial: Drop "in original [key] insertion order" (#2330)
- [ ] [`46f83b6`](https://github.com/tc39/ecma262/commit/46f83b6) Editorial: Change "non-negative integer" to "integer" (#2330)
- [ ] [`5ad43c4`](https://github.com/tc39/ecma262/commit/5ad43c4) Editorial: Change "that satisfies" to "such that" (#2330)
- [ ] [`94c6c6b`](https://github.com/tc39/ecma262/commit/94c6c6b) Editorial: Fix mistakes (#2331)

**Comment by Jack-Works** [comment]
close for housekeeping for now, I'm monitoring the ecma262 repo for any new PRs merged, but for old PRs, I'll update them to match the spec while it is touched (by other PRs or proposals).
