### ISSUE TITLE
Refactors TODO

### ISSUE THREAD

**Issue by Jack-Works** [engine262/engine262#216]
Possible refactors listed below should not start before all codebases are converted to typed files, also need to discuss each case in the PR first.

- [ ] Split `PropertyDefinition` into two interfaces. It contains two unrelated productions.
- [ ] Rename `readonly A: BitwiseANDExpressionOrHigher;` to something like `Left` and `Right`.
- [ ] Rename `readonly Expression_a?: Expression;` to something meaningful.
- [ ] `ForAwaitStatement` can merge with `ForOfStatement`.

**Comment by Jack-Works** [comment]
not sure if we still need this now, but I'm not focusing on this recently, so closing for now
